#
# Simply copy these function sources to the deployment directory
#

build-AuthFunction:
	cd auth/ && cp *.js $(ARTIFACTS_DIR)/

build-LoginFunction:
	cd login/ && cp *.js $(ARTIFACTS_DIR)/

build-LogEventFunction:
	cd log-event/ && cp *.js $(ARTIFACTS_DIR)/

build-InfoFunction:
	cd info/ && cp *.js $(ARTIFACTS_DIR)/

build-AddLocationFunction:
	cd add-location/ && cp *.js $(ARTIFACTS_DIR)/

build-DanielFunction:
	cd daniel/ && cp *.js $(ARTIFACTS_DIR)/

build-GetLocationFunction:
	cd get-location/ && cp *.js $(ARTIFACTS_DIR)/

build-GetUploadLinkFunction:
	cd get-upload-link/ && cp *.js $(ARTIFACTS_DIR)/

build-DBInitFunction:
	cd db-init/ && cp *.js $(ARTIFACTS_DIR)/

build-DBRunFunction:
	cd db-run/ && cp *.js $(ARTIFACTS_DIR)/

build-CloudfrontGeolocationFunction:
	cd cloudfront-geolocation/ && cp *.js $(ARTIFACTS_DIR)/
