#!/usr/bin/env bash

# MacOS by default has BSD grep, and brew installs GNU grep as ggrep
if command -v ggrep &>/dev/null; then
  grep="ggrep"
else
  grep="grep"
fi

if [ -e samconfig.toml ]; then
  echo The file samconfig.toml exists
  echo
  echo If you actually mean to initialize the configuration for this deployment, move or delete the existing file

  exit 1
fi

# Text highlighting escape sequences
__hi="\e[33m"
__endhi="\e[0m"

profiles=$([ -e ~/.aws/credentials ] && $grep -Po '(?<=^\[).+(?=\]$)' < ~/.aws/credentials)

if [ ${#profiles} -eq 0 ]; then
  echo No AWS profiles defined in ~/.aws/credentials
  echo
  echo -e "${__hi}If you configure your AWS profile manually by running \`aws configure\`, the profile used for deployment"
  echo -e "can then be manually added to the samconfig.toml file under [default.deploy.parameters]$__endhi"
else
  echo Your configured AWS profiles:
  echo
  echo "$profiles"
  echo
  echo Which AWS profile would you like to use for deployment?
  echo

  read -rp "> " profile

  if [ -z "$profile" ]; then
    echo
    echo Profile must be specified

    exit 1
  fi

  echo
  echo Using profile: "$profile"
fi

echo
echo Creating initial configuration...
echo
echo -n "Generating strong passwords for database access and administration"

function pw () {
  ./manage gen-rds-db-password
}

p1="DBAdminPassword=\\\"$(pw)\\\""  && echo -n .
p2="DBWriterPassword=\\\"$(pw)\\\"" && echo -n .
p3="DBReaderPassword=\\\"$(pw)\\\"" && echo -n .

echo \ done
echo

cp -v .config-templates/* .

echo
echo Writing initial configuration...

echo profile = \""$profile"\" >> samconfig.toml
echo parameter_overrides = \""$p1" "$p2" "$p3"\" >> samconfig.toml

echo
echo Created: samconfig.toml
